basePath: /
host: localhost:8080
info:
  contact:
    email: support@vave-tool.com
    name: API Support
  description: A Go-based backend service that provides REST and gRPC APIs for managing
    products.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: Vave Tool API
  version: "1.0"
paths: {}
schemes:
- http
swagger: "2.0"
